### ISSUE TITLE
Which model of Roomba did you demo with?

### ISSUE THREAD

**Issue by jimkang** [cliffano/roombox#1]
Hi, I'm interested in trying this project out (and getting started with Roomba hacking in general). I have a [Roomba 650](http://store.irobot.com/irobot-roomba-650/product.jsp?productId=13081980). Do you have any idea if this module + a RooTooth and a Roomba 650 will work? Which Roomba did you use?

**Comment by cliffano** [comment]
@jimkang I was using an old Roomba 500. Rather than using roombox straight away, I would recommend you to use node-roomba instead https://www.npmjs.com/package/roomba , and try to start the Roomba device just to be sure that it's compatible.

I vaguely remember finding a web page with various Roomba Open Interface versions (or the equivalence for later versions of Roomba). You can compare the spec b/w 500 and 650.
If they are, you need to come up with the config for 650. Here's where node-roomba sets up ROI for Roomba 500 https://github.com/mharsch/node-roomba/blob/master/protocol/roi.js .

At the end of the day, it's simply about sending data through serial port.
All the best and have fun! Let me know if you have any other questions.

**Comment by jimkang** [comment]
@cliffano Thanks so much for all that information! I've been unable to find definitive confirmation as to whether the 650 supports the Roomba Open Inferface or the Create Open Interface, so I may just gamble on a RooTooth and see what happens.

**Comment by cliffano** [comment]
No problem. Feel free to ping if you made any progress on your Roomba adventure.
Closing this issue for now.
